/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.28
 * Generated at: 2018-03-24 08:39:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mainAdmin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/etc/header.jsp", Long.valueOf(1521805082270L));
    _jspx_dependants.put("/views/etc/footer.jsp", Long.valueOf(1521792753060L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("\r\n");
      out.write("<link href=\"/classKing/css/reset.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\" integrity=\"sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm\" crossorigin=\"anonymous\">\r\n");
      out.write("<link href=\"/classKing/css/main.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link href=\"/classKing/css/admin.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<script src=\"/classKing/js/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("<script defer\r\n");
      out.write("\tsrc=\"https://use.fontawesome.com/releases/v5.0.8/js/all.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Owl Stylesheets -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/owlcarousel/owl.carousel.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/owlcarousel/owl.carousel.min.css\">\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("<!-- javascript -->\r\n");
      out.write("<script src=\"/classKing/resources/owlcarousel/owl.carousel.js\"></script>\r\n");
      out.write("<script src=\"/classKing/resources/owlcarousel/owl.carousel.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\t$(document).ready(function(){\t  \r\n");
      out.write("\t\t$('.owl-carousel').owlCarousel({\r\n");
      out.write("\t\t    loop:true,\r\n");
      out.write("\t\t    nav:true,\r\n");
      out.write("\t\t\tautoWidth: false,\r\n");
      out.write("\t\t    navText: [$('.btn-next'),$('.btn-prev')],\r\n");
      out.write("\t\t    responsive:{\r\n");
      out.write("\t\t        0:{\r\n");
      out.write("\t\t            items:1\r\n");
      out.write("\t\t        },\r\n");
      out.write("\t\t        600:{\r\n");
      out.write("\t\t            items:3\r\n");
      out.write("\t\t        },\r\n");
      out.write("\t\t        1000:{\r\n");
      out.write("\t\t            items:4\r\n");
      out.write("\t\t        }\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<title>Class King</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>header</title>\r\n");
      out.write("<link href=\"/classKing/css/header.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<header>\r\n");
      out.write("\t\t<div id=\"top\">\r\n");
      out.write("\t\t\t<a href=\"/classKing/main.jsp\"><img src=/classKing/images/logo01.png></a>\r\n");
      out.write("\t\t\t<div class=\"top_right\">\r\n");
      out.write("\t\t\t\t<div class=\"box_search\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"tf_search\" class=\"tf_search\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"검색어 입력\" />\r\n");
      out.write("\t\t\t\t\t<button type=\"submit\" class=\"btn_search\" onclick=\"location.href='/classKing/views/search/search.jsp'\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"ico_search\">검색</span>\r\n");
      out.write("\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<section>\r\n");
      out.write("\t<div id=\"wrap\">\t   \r\n");
      out.write("\t    \r\n");
      out.write("\t\t<div id=\"right_box\">\r\n");
      out.write("\t\t\t<!-- 어드민 박스 시작 -->\r\n");
      out.write("\t\t\t<div id=\"admin_box\">\r\n");
      out.write("\t\t\t\t<table class=\"user_table\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td colspan=\"2\" id=\"user_img\"><img src=\"images/user.png\">\r\n");
      out.write("\t\t\t\t\t\t\t<span class=\"username\">김연아님, 반갑습니다.</span></td>\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><a href=\"/classKing/views/member/memberMypage.jsp\"><img src=\"images/setting.png\"></a><p>설정</p></td>\r\n");
      out.write("\t\t\t\t\t\t<td><a href=\"#\"><img src=\"images/logout.png\"></a><p>로그아웃</p></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<hr class=\"hr_gray\">\r\n");
      out.write("\t\t\t\t<div class=\"admin_menu\">\r\n");
      out.write("\t\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/classKing/views/admin/adminClass.jsp\"><i class=\"fas fa-angle-right\"></i> 클래스 관리</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"/classKing/views/admin/adminMember.jsp\"><i class=\"fas fa-angle-right\"></i> 회원 관리</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- 어드민 박스 끝 -->\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- 알람박스 시작 -->\r\n");
      out.write("\t\t\t<div id=\"alarm_box\">\r\n");
      out.write("\t\t\t알람!\t\r\n");
      out.write("\t\t\t</div>\t\t\t\t\r\n");
      out.write("\t\t    <!-- 알람박스 끝 -->\r\n");
      out.write("\t\t</div>\t\r\n");
      out.write("\t \t<div id=\"left_box\" style=\"border:none\">\r\n");
      out.write("\t \t\t<!-- 공지사항 -->\r\n");
      out.write("\t \t\t<img src=\"images/notice2.jpg\">\r\n");
      out.write("\t \t\t<div id=\"notice_box\">\t \t\t\t\r\n");
      out.write("\t \t\t\t<p>공지사항<span class=\"btn_more\"><a href=\"#\">more <i class=\"fas fa-angle-right\" style=\"vertical-align:middle;\"></i></a></span></p>\t \t\t\t\r\n");
      out.write("\t \t\t\t<ul>\r\n");
      out.write("\t \t\t\t\t<li><a href=\"#\">클래스킹 업데이트에 따른 시스템 점검 안내</a><span class=\"notice_date\">2018-01-02</span></li>\r\n");
      out.write("\t \t\t\t\t<li><a href=\"#\">클래스킹 업데이트에 따른 시스템 점검 안내</a><span class=\"notice_date\">2018-01-02</span></li>\r\n");
      out.write("\t \t\t\t\t<li><a href=\"#\">클래스킹 업데이트에 따른 시스템 점검 안내</a><span class=\"notice_date\">2018-01-02</span></li>\r\n");
      out.write("\t \t\t\t\t<li><a href=\"#\">클래스킹 업데이트에 따른 시스템 점검 안내</a><span class=\"notice_date\">2018-01-02</span></li>\r\n");
      out.write("\t \t\t\t\t<li><a href=\"#\">클래스킹 업데이트에 따른 시스템 점검 안내</a><span class=\"notice_date\">2018-01-02</span></li>\r\n");
      out.write("\t \t\t\t</ul>\t \t\t\t\r\n");
      out.write("\t \t\t</div>\r\n");
      out.write("\t \t\t\r\n");
      out.write("\t \t\t<!-- 추천클래스 -->\r\n");
      out.write("\t \t\t<div id=\"best_class\">\r\n");
      out.write("\t \t\t\t<p>추천 클래스</p>\r\n");
      out.write("\t\t\t\t<div class=\"card-group\">\r\n");
      out.write("\t\t\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card-img-top\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"images/best_c.png\" alt=\"Card image cap\" class=\"circle\">\r\n");
      out.write("\t\t\t\t\t\t</div>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t\t<h5 class=\"card-title\">클래스 이름</h5>\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"card-text\">이 클래스는 클래스킹을 위한 클래스이며 클래스를 위한 클래스\r\n");
      out.write("\t\t\t\t\t\t\t공부 열심히 하기 위한 클래스임</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card-img-top\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"images/best_c.png\" alt=\"Card image cap\" class=\"circle\">\r\n");
      out.write("\t\t\t\t\t\t</div>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t\t<h5 class=\"card-title\">클래스 이름</h5>\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"card-text\">이 클래스는 클래스킹을 위한 클래스이며 클래스를 위한 클래스\r\n");
      out.write("\t\t\t\t\t\t\t공부 열심히 하기 위한 클래스임</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"card\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card-img-top\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"images/best_c.png\" alt=\"Card image cap\" class=\"circle\">\r\n");
      out.write("\t\t\t\t\t\t</div>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t\t\t<h5 class=\"card-title\">클래스 이름</h5>\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"card-text\">이 클래스는 클래스킹을 위한 클래스이며 클래스를 위한 클래스\r\n");
      out.write("\t\t\t\t\t\t\t공부 열심히 하기 위한 클래스임</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div> \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- 마이클래스 -->\t\t\t\r\n");
      out.write("\t\t\t<div id=\"my_class\" class=\"slider\">\r\n");
      out.write("\t \t\t\t<p>마이 클래스</p>\t \t \r\n");
      out.write("\t \t\t\t<ul id=\"ul_mc\" class=\"owl-carousel owl-theme\" style=\"padding:0px 20px\">\r\n");
      out.write("\t \t\t\t\t<li class=\"item\">\r\n");
      out.write("\t \t\t\t\t\t<div class=\"class_img_top\" style=\"margin:none;\">\r\n");
      out.write("\t \t\t\t\t\t\t<a href=\"#\"><i class=\"fas fa-plus\"></i></a>\r\n");
      out.write("\t \t\t\t\t\t</div>\r\n");
      out.write("\t \t\t\t\t\t<p>클래스 만들기</p>\t \t\t\t\t\t\r\n");
      out.write("\t \t\t\t\t</li>\r\n");
      out.write("\t \t\t\t\t<li class=\"item\">\r\n");
      out.write("\t \t\t\t\t\t<div class=\"class_img_top\" style=\"margin:none;\">\r\n");
      out.write("\t \t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t \t\t\t\t\t\t\t<img src=\"images/best_c.png\">\r\n");
      out.write("\t \t\t\t\t\t\t</a>\r\n");
      out.write("\t \t\t\t\t\t</div>\r\n");
      out.write("\t \t\t\t\t\t<p>클래스 이름1</p>\t \t\t\t\t\t\r\n");
      out.write("\t \t\t\t\t</li>\r\n");
      out.write("\t \t\t\t\t<li class=\"item\">\r\n");
      out.write("\t \t\t\t\t\t<div class=\"class_img_top\" style=\"margin:none;\">\r\n");
      out.write("\t \t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t \t\t\t\t\t\t\t<img src=\"images/best_c.png\">\r\n");
      out.write("\t \t\t\t\t\t\t</a>\r\n");
      out.write("\t \t\t\t\t\t</div>\r\n");
      out.write("\t \t\t\t\t\t<p>클래스 이름2</p>\t \t\t\t\t\t\r\n");
      out.write("\t \t\t\t\t</li>\r\n");
      out.write("\t \t\t\t\t<li class=\"item\">\r\n");
      out.write("\t \t\t\t\t\t<div class=\"class_img_top\" style=\"margin:none;\">\r\n");
      out.write("\t \t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t \t\t\t\t\t\t\t<img src=\"images/best_c.png\">\r\n");
      out.write("\t \t\t\t\t\t\t</a>\r\n");
      out.write("\t \t\t\t\t\t</div>\r\n");
      out.write("\t \t\t\t\t\t<p>클래스 이름3</p>\t \t\t\t\t\t\r\n");
      out.write("\t \t\t\t\t</li>\r\n");
      out.write("\t \t\t\t\t<li class=\"item\">\r\n");
      out.write("\t \t\t\t\t\t<div class=\"class_img_top\" style=\"margin:none;\">\r\n");
      out.write("\t \t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t \t\t\t\t\t\t\t<img src=\"images/best_c.png\">\r\n");
      out.write("\t \t\t\t\t\t\t</a>\r\n");
      out.write("\t \t\t\t\t\t</div>\r\n");
      out.write("\t \t\t\t\t\t<p>클래스 이름4</p>\t \t\t\t\t\t\r\n");
      out.write("\t \t\t\t\t</li>\r\n");
      out.write("\t \t\t\t</ul>\r\n");
      out.write("\t\t\t\t<div class=\"owl-nav\">\r\n");
      out.write("\t\t\t\t\t<div class=\"btn-prev\"><i class=\"fas fa-caret-left\"></i></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"btn-next\"><i class=\"fas fa-caret-right\"></i></div>\t\t\t\r\n");
      out.write("\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t \t</div><!-- right box 끝 -->\r\n");
      out.write("\t \t\r\n");
      out.write("\t\t</div><!-- wrap 끝 -->\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t</section>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>footer</title>\r\n");
      out.write("<link href=\"/classKing/css/footer.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<footer>\r\n");
      out.write("\t\t<div class=\"footer\">\r\n");
      out.write("\t\t\t<a href=\"/classKing/views/notice/notice.jsp\">공지사항 ㅣ</a>\r\n");
      out.write("\t\t\t<a href=\"/classKing/views/qna/qna.jsp\">Q&A </a><br>\r\n");
      out.write("\t\t\tCOPYRIGHT(C) 2018 CLASS KING. ALL RIGHTS RESERVED.\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
